file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/Selman/.gitconfig	core.autocrlf=true
file:C:/Users/Selman/.gitconfig	core.editor="C:\Users\Selman\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
file:C:/Users/Selman/.gitconfig	user.name=MSelmanSavas
file:C:/Users/Selman/.gitconfig	user.email=selmansavas@agave.games
file:C:/Users/Selman/.gitconfig	difftool.sourcetree.cmd='C:/Users/Selman/AppData/Local/Programs/Microsoft VS Code/Code.exe' --diff --wait $LOCAL $REMOTE
file:C:/Users/Selman/.gitconfig	mergetool.sourcetree.cmd='C:/Users/Selman/AppData/Local/Programs/Microsoft VS Code/Code.exe' -n --wait $MERGED
file:C:/Users/Selman/.gitconfig	mergetool.sourcetree.trustexitcode=true
file:C:/Users/Selman/.gitconfig	credential.helperselector.selected=manager
file:C:/Users/Selman/.gitconfig	credential.helper=store
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/MSelmanSavas/EntitySystem.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
